name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: bun setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build Project
        run: bun i && bun b

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: gitsunmin
          user_email: tjsals116@gmail.com
